# Generated by Django 6.0 on 2025-12-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('makeup', 'Makeup'), ('skincare', 'Skincare'), ('fragrance', 'Fragrance'), ('haircare', 'Haircare'), ('sunscreen', 'Sunscreen'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
